### ISSUE TITLE
可否在调用播放器时加上header参数？

### ISSUE THREAD

**Issue by imzf** [LiuLang/bcloud#100]
我发现在播放某些视频文件时会很卡，20kb/s 左右浮动。之后我尝试用wget下载视频文件，发现也很卡。我觉得可能是百度对某些文件进行了限速，于是我尝试加了一些参数：
mpv --http-header-fields='User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35.0','Referer: http://pan.baidu.com/disk/home','Connection: keep-alive' "url"
果然速度好了很多,一点也不卡了，用系统监视器查看了下速度，1mb/s 很稳定。
所以，我希望能够在 bcloud 调用播放器时加上 header 参数

**Comment by imzf** [comment]
问题已解决 [让 BCloud 播放视频更流畅](http://imzf.gitcafe.io/2015/04/05/%E8%AE%A9-BCloud-%E6%92%AD%E6%94%BE%E8%A7%86%E9%A2%91%E6%9B%B4%E6%B5%81%E7%95%85/)

**Comment by Firef0x** [comment]
@imzf  我看到 BCloud 用的是 [这一个 UA 字符串](https://github.com/LiuLang/bcloud/blob/master/bcloud/const.py#L20)，但是据卡饭网友说用百度云管家的 UA 字符串 `netdisk;4.4.0.6;PC;PC - Windows;6.2.9200;WindowsBaiduYunGuanJia` 会更快。不知道你感觉怎样？

**Comment by mhohai** [comment]
@Firef0x 我感觉速度上不会有太大区别，都是百度云的UA，只是版本略有不同！

**Comment by imzf** [comment]
@Firef0x  试了一下，效果差不多
