### ISSUE TITLE
如果不设置 DownloadPage里面的 document-open-symbolic尺寸，程序在我机器上就无法继续执行。

### ISSUE THREAD

**Issue by wxg4net** [LiuLang/bcloud#105]
补丁
https://github.com/wxg4net/bcloud/commit/f6488a10ee20cee5392e55b505a7903782b0a468

**Comment by LiuLang** [comment]
这个之前提交(https://github.com/LiuLang/bcloud/commit/13b7ce637a1fedcf95e77407a4dea41fdae22ec8)时, 引入的一个bug, 因类已经指定了image property, 就不再需要设定icon name属性了. 而且, new_from_icon_name()是在gtk3.12中引入的, 与之前的gtk版本不兼容.

只需要回滚到之前的状态就行了, 已经修复, 谢谢你的反馈.
