### ISSUE TITLE
代理上网环境无法使用正常登录

### ISSUE THREAD

**Issue by danzeng** [LiuLang/bcloud#107]
在单位代理上网，系统为Deepin linux2014.2 
设置apt.conf文件
/etc/apt.conf
Acquire::http::proxy "http://10.20.1.16:808"; 
Acquire::https::proxy "https://10.20.1.16:808"; 
Acquire::ftp::proxy "ftp://10.20.1.16:21"; 

在终端运行：bcloud-gui 一直处于登录认证。最后提示“登录失败”
[Errno 110] 连接超时
[Errno 110] 连接超时
[Errno 110] 连接超时
Error in on_wap_signin(): None None

请问要如何解决？

**Comment by danzeng** [comment]
6.如何设置代理? bcloud支持桌面的全局代理设置, 比如在Gnome的网络设置里面可以加入代理. 也可以在终端里设置代理, 比如 export http_proxy='http://127.0.0.1:8086' 来设定 http代理, export https_proxy='http://127.0.0.1:8086' 来设定https代理, 设定完 之后, 在这个终端里运行 $ bcloud-gui, 这时, bcloud就会使用刚刚设定的网络代理.

要注意的是, bcloud的部分网络连接要求使用https, 这就要求你设定https代理后, 同时 导入相应的证书, 不然会出现错误.

按照第6条，试过了。仍然错误依旧。
现在有三个问题：
1、8086端口，是否需要修改为我的代理上网端口“808”。我不明白此处8086端口是固定端口还是根据实际情况更改。
2、如何导入相应的证书。
3、是否每次启动都要在终端中进行。

能不能在UI窗口中提供代理上网设置。

另外非常感谢您能给大家提供这个软件，真是相当的好用。比Mac下的百度云同步盘好用多了。

**Comment by LiuLang** [comment]
1. 导入证书, 需要导入到系统里面. 目前还没有好用的证书管理工具, 所以需要手动操作了. 把证书放到/usr/share/ca-certificates/mozilla或者其它目录里, 要保证其扩展名为crt, 然后启用这个证书: # dpkg-reconfigure ca-certifcates

2. 在UI里面设置代理, 比如gnome的网络设置里面都是可以的, 这是全局有效的.

**Comment by danzeng** [comment]
![deepinscreenshot20150108121044](https://cloud.githubusercontent.com/assets/10398342/5657766/4f1035e6-972f-11e4-8dbe-f73aa07e509e.png)

我已经在deepin linux 2014.2中的控制台设置了代理。但是只对网页浏览器有效，对部分软件却不能实现。

证书倒入到谷歌浏览器和火狐浏览器就可以吗？
从哪里下载证书呢？

**Comment by LiuLang** [comment]
没测试过deepin, 不了解, 但在gnome和kde中是可以的.
证书需要导入到系统目录, 上面已经说明了步骤.
证书是你的https代理服务器生成的. 如果不明白的话, 可以联系你的系统管理员, 向他索要证书.

**Comment by danzeng** [comment]
deepin就是gnome的桌面。但确实不能实现全局代理。
