### ISSUE TITLE
能否不显示头像？

### ISSUE THREAD

**Issue by imzf** [LiuLang/bcloud#108]
头像的位置太别扭了，能否不显示？或者换一个位置如图标处
![2015-01-08 19 01 47](https://cloud.githubusercontent.com/assets/3401994/5661669/61fce4ee-9769-11e4-9773-7226d8683d93.png)

**Comment by LiuLang** [comment]
左上角空间太小, 而且上面的控制栏按纽只有gtk3.12 之后才会被使用, 旧版的系统里面是没有的.
当初加入用户的头像主要是为了区分当前用户. 因为我在测试时要来回切换多个用户, 很容易搞混, 所以就加入了这个头像.

我周末改一下, 在"首选项"里加入一个选项, 这样就可以控制是否显示头像了.

**Comment by imzf** [comment]
谢谢，更新速度好快！

**Comment by LiuLang** [comment]
周末没多少事儿, 就很早推送上来了.
