### ISSUE TITLE
注销再登录后状态图标消失

### ISSUE THREAD

**Issue by pingplug** [LiuLang/bcloud#111]
环境：GNOME 3.14， Arch Linux 64位， 官方源和AUR都是如此，IPv6，所有帐号均设置显示状态图标

一开始打开的时候是有状态图标的，注销后再次登录（另一帐号）后状态图标消失，关闭窗口后bcloud依然在运行，依然有通知，但是点击通知没有反应。而且再次登录后bcloud也更容易崩溃（可能是错觉？）

**Comment by LiuLang** [comment]
On 01/14/2015 10:59 AM, pingplug wrote:
> 环境：GNOME 3.14， Arch Linux 64位， 官方源和AUR都是如此，IPv6，所有帐号均设置显示状态图标
>
> 一开始打开的时候是有状态图标的，注销后再次登录（另一帐号）后状态图标消失，关闭窗口后bcloud依然在运行，依然有通知，但是点击通知没有反应。而且再次登录后bcloud也更容易崩溃（可能是错觉？）
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LiuLang/bcloud/issues/111
>
"状态图标" 是桌面左上角/左下角的那个系统托盘里面的图标吗? 这个是可以设置 
的, 每个用户都有自己的设置属性, 可能不一样. 你在"首选项"里面找一下.

**Comment by pingplug** [comment]
![2015-01-15 09 38 05](https://cloud.githubusercontent.com/assets/6712475/5751187/fb1b25e2-9c9a-11e4-9e64-52dbefd03778.png)
![2015-01-15 09 38 51](https://cloud.githubusercontent.com/assets/6712475/5751188/fb2298fe-9c9a-11e4-8107-22a56b8ba78c.png)
是指这个“使用状态图标”吗？如我最开始所说的，所有帐号都设置了
如果再次登录的是同一个帐号，可能图标还在，但是一旦换了一个帐号，图标一定消失。这个问题在我这里每次都能重现，至少几十次了

**Comment by LiuLang** [comment]
"使用状态图标", 这个翻译的有问题, 应该叫做"最小化到系统托盘". 我抽空改一下.
这个是需要把bcloud退出后重启才会有效果的, 所以切换帐户后没有效.

**Comment by mhohai** [comment]
@pingplug 翻译问题，你舍得不自己修改下么？ :hammer:

**Comment by pingplug** [comment]
@mhohai 翻译不是问题，我只是不理解切换帐号无效这件事
