### ISSUE TITLE
请问如何查看bcloud的log

### ISSUE THREAD

**Issue by sbw983** [LiuLang/bcloud#117]
RT

最近用bcloud登陆网盘下文件老是中断然后状态显示为error，但是不知道是何种错误，在terminal中情动bcloud也看不出出错信息，请问如何检查bcloud的log？，谢谢

**Comment by LiuLang** [comment]
位于 ~/.config/bcloud/bcloud.log.

**Comment by EricInBj** [comment]
太好了，看了一下日志，明白了为啥我的登录界面不能勾选记住密码和自动登录。

sudo easy_install3 keyring 搞定。

感谢作者。

**Comment by LiuLang** [comment]
你的是哪个系统.
deb包, rpm, 或者arch的系统, 都会自动处理依赖关系的.

**Comment by libertas** [comment]
在Arch的KDE下貌似也不能正确的保存密码。（依赖KWallet?)
