### ISSUE TITLE
Ubuntu 12.04 64bit 登陆问题

### ISSUE THREAD

**Issue by hubberwisdom** [LiuLang/bcloud#118]
谢谢作者开发这个工具！

系统为ubuntu 12.04 64bit，在bcloud-packages下载了deb安装包之后，装好了，但是在登录界面的那个 记住密码 和 自动登录 都是灰色，不能选择。而且输入了用户名和密码之后按登录也没有反应。

在终端使用sudo bcloud-gui之后，出现如下错误：
ERROR:dbus.proxies:Introspect error on :1.2:/org/freedesktop/secrets/aliases/default: dbus.exceptions.DBusException: org.freedesktop.Secret.Error.NoSuchObject: The '/org/freedesktop/secrets/aliases/default' object does not exist
ERROR:dbus.connection:Unable to set arguments ({'org.freedesktop.Secret.Item.Label': 'utest @ test', 'org.freedesktop.Secret.Item.Attributes': {'username': 'utest', 'service': 'test'}}, dbus.Struct((dbus.ObjectPath('/org/freedesktop/secrets/session/s2'), '', dbus.ByteArray(b'ptest'), 'text/plain'), signature=None), True) according to signature None: <class 'TypeError'>: Expected a string or unicode object
而且出来的那个登录界面也和之前描述的一样无法登录。

请问是系统问题吗？求指导！谢谢！

**Comment by LiuLang** [comment]
ubuntu 12.04请参考这里的说明: https://github.com/LiuLang/bcloud-packages#ubuntu-1204-%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97
