### ISSUE TITLE
ubuntu 14.04 无法登录

### ISSUE THREAD

**Issue by cosmanleo** [LiuLang/bcloud#119]
安装上后登录提示：
Failed to get BAIDUID cookie, please try agin (应该为again吧？)
如下图（我已经删去用户名和密码）
![image](https://cloud.githubusercontent.com/assets/10735398/5932245/e9b8e9b6-a6e4-11e4-80c6-8fb06c4a084c.png)

**Comment by LiuLang** [comment]
是的, 这个是写错了的, 我晚上回去后就修正, 多谢你的反馈.

**Comment by cosmanleo** [comment]
谢谢回复！
不过我真正想反映的是，用户名和密码都没输错，为什么会出这个错误提示？多谢！

**Comment by LiuLang** [comment]
你可以重新输一下试试, 看行不行.
还有, 你的帐户绑定了手机号了么? 目前bcloud还不支持手机验证

**Comment by cosmanleo** [comment]
![image](https://cloud.githubusercontent.com/assets/10735398/5996055/a6649188-aadb-11e4-823d-8dd1af145818.png)

帐号没有手机绑定，试了很多次还是登不上去。

**Comment by LiuLang** [comment]
请在pan.baidu.com 里面试着登录一下, 看有没有问题.

**Comment by cosmanleo** [comment]
在pan.baidu.com里面登录没有问题

**Comment by cosmanleo** [comment]
是否是因为密码中包含特殊字符，而程序没有正确识别或提交？

**Comment by LiuLang** [comment]
和特殊字符没关系, 我测试了这个密码&_*?;<>&0a:.~, 也是可以正常登录的.

**Comment by mfkddcwy** [comment]
Fedora 21 也一样，求解。

**Comment by mhohai** [comment]
我特意在本机试过了，登录没有问题...

**Comment by mfkddcwy** [comment]
今天居然就登陆上去了，lol
