### ISSUE TITLE
增加文件排序功能

### ISSUE THREAD

**Issue by imzf** [LiuLang/bcloud#120]
bcloud 不支持像文件管理器一样按名称排列、按大小排列（如图），很不方便
![2015-01-28 15 40 33](https://cloud.githubusercontent.com/assets/3401994/5934065/b48ec984-a704-11e4-81a6-297065ad66d6.png)

**Comment by LiuLang** [comment]
把显示模式切换为列表模式, 然后就可以点击列表表头了, 比如"文件名", "文件大小", "日期"等.

**Comment by imzf** [comment]
@ LiuLang 明白了，之前一直没注意到有这个功能。不过我更习惯网格视图，能否在右键菜单里添加选择文件排序的功能，或者在工具栏添加也可以

**Comment by LiuLang** [comment]
这个功能暂时不会加入的

**Comment by LiuLang** [comment]
这个功能暂时不会加入的
