### ISSUE TITLE
百度离线下载的链接问题

### ISSUE THREAD

**Issue by NERDTHE** [LiuLang/bcloud#124]
百度离线的下载好像由原来的lx.cdn.baidupcs.com变为了cdn.baidupcs.com。

**Comment by imzf** [comment]
不同的文件链接也是不同的

**Comment by Firef0x** [comment]
@Nopeh @imzf ，你好！

有 `lx` 前缀的是使用蓝汛 CDN 的，卡饭上有人说改成 `qd` 更加快。你们感觉呢？
见 [百度网盘点击"下载"按钮几率性无反应](http://bbs.kafan.cn/thread-1804863-1-1.html)

此致！ :bow:

**Comment by imzf** [comment]
@Firef0x  你好，不同地区，不同运营商，不同dns所解析到的ip都是不同的。如果你是江苏移动宽带用户的话，我的文章[解决移动宽带下百度云下载速度慢的问题](http://imzf.gitcafe.io/2015/04/05/%E8%A7%A3%E5%86%B3%E7%A7%BB%E5%8A%A8%E5%AE%BD%E5%B8%A6%E4%B8%8B%E7%99%BE%E5%BA%A6%E4%BA%91%E4%B8%8B%E8%BD%BD%E9%80%9F%E5%BA%A6%E6%85%A2%E7%9A%84%E9%97%AE%E9%A2%98/)应该可以帮到你。如果不是的话请参考[zhaoxiting1997的回复](https://v2ex.com/t/181713), 寻找适合自己的服务器地址。

**Comment by Firef0x** [comment]
@imzf 认真看了你的文章以及回复，感觉很有道理。看来 `qd` 应该是青岛的意思，估计那位网友是青岛那边的。既然要找 IP 的话，那还是顺其自然，让百度的 CDN 调度吧，IP 地址也不一定保证以后一直是最快的。

**Comment by imzf** [comment]
@Firef0x 如果能够正常使用的话，肯定是不修改的好，可问题是百度与网易使用的 cdn 服务是有问题的，像 nj.baidupcs.com，不管你什么地区什么运营商，都被解析到江苏南京电信服务器，这样肯定有的地区（运营商)效果会不好。不修改的话，我这里下载百度云的文件基本上可以算是龟速，网易云音乐 mv 一卡一卡的，根本没法看。至于说 ip 有效性对我根本不算问题，失效就折腾一下，重新找个 ip。

**Comment by garylab** [comment]
100M 长城宽带，百度云盘下载速度：50K/s 龟速，换360云盘3M/s，爽死了
建议直接用360的好了

**Comment by vipzrx** [comment]
有破解限速版本的。我win下是可以的

话说，新浪微盘6月30号，要停止服务了

**Comment by Firef0x** [comment]
@yeszao 360 现在恶心得要登录转存了。

@vipzrx 你说的是 Windows 的百度云管家？
