### ISSUE TITLE
linux mint 17.1为什么界面跟readme里的截图不一样？

### ISSUE THREAD

**Issue by wzhy90** [LiuLang/bcloud#136]
感觉截图里面用 了gtk3界面，但是我这里没有，是需要安装什么包吗？

**Comment by LiuLang** [comment]
On 03/30/2015 12:06 PM, wzhy90 wrote:
> 感觉截图里面用 了gtk3界面，但是我这里没有，是需要安装什么包吗？
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LiuLang/bcloud/issues/136
>
请参考 https://github.com/LiuLang/bcloud/#qa 第4条, 里面有说明的
