### ISSUE TITLE
怎么调出配置截面

### ISSUE THREAD

**Issue by fsyxhua** [LiuLang/bcloud#143]
想修改默认下载目录，去哪儿修改，配置文件在什么地方

**Comment by libertas** [comment]
左上角有个绿色按钮，按了之后，找到preference

**Comment by fsyxhua** [comment]
我的怎么么有绿色按钮，不过我在 .config/bcloud目录下面找到了配置文件，修改成功了，你说的绿色按钮实在登录的时候的界面还是进去后界面。。。
