### ISSUE TITLE
请求兼容mac

### ISSUE THREAD

**Issue by transtone** [LiuLang/bcloud#153]
osx下的百度网盘只有同步盘，没有云管家。而bcloud更像windows下的百度云管家。因此兼容mac也是很有必要的。

**Comment by LiuLang** [comment]
On 05/29/2015 09:33 PM, transtone wrote:
> osx下的百度网盘只有同步盘，没有云管家。而bcloud更像windows下的百度云管家。因此兼容mac也是很有必要的。
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LiuLang/bcloud/issues/153
>
目前没有类似的计划

**Comment by mhohai** [comment]
开源的，如果只是支持mac，你解决下依赖，然后pull reqire上来吧。

开源 == 自己动手，丰衣足食。

**Comment by maxfu** [comment]
请问这个是不是使用纯Python写的？多谢。

**Comment by gshmu** [comment]
@maxfu 我也不知道，我为什么会浪费时间。
![2016-03-29t09 55 18_001](https://cloud.githubusercontent.com/assets/1797676/14095583/6f85c1aa-f594-11e5-9bf3-f30b971ed2b3.png)
