### ISSUE TITLE
为什么你使用GTK+ 3.0，而不是PYGTK（GTK 2.0）?

### ISSUE THREAD

**Issue by mudongliang** [LiuLang/bcloud#154]
如题

**Comment by imzf** [comment]
GTK 2连个好看的主题都没有。。。。。

**Comment by mudongliang** [comment]
能不能从技术层面上分析这个问题啊？比如说考虑平台兼容啊什么的！

2015-06-11 19:57 GMT+08:00 张飞 <notifications@github.com>:

**Comment by libertas** [comment]
pygtk不是已经停止开发了吗

**Comment by laichiaheng** [comment]
美觀在圖形介面下是有很重要的意義的！

**Comment by bingosxs** [comment]
New users wishing to develop Python applications using GTK+ are recommended to use the GObject-Introspection features available in PyGObject.
Existing authors of PyGTK applications are also recommended to port their applications to PyGObject to take advantage of new features appearing in GTK-3 and beyond. More information on PyGObject and GObject-Introspection can be found at http://live.gnome.org/PyGObject.

**Comment by LiuLang** [comment]
2013年的时假, gtk2.0的主题显示效果要比gtk3.0的差一些, 而且当时可以直接用CSS3来自定义gtk3的样式, 所以为了好看, 就用了gtk3
