### ISSUE TITLE
在线看视频不流畅

### ISSUE THREAD

**Issue by BEIBEI123** [LiuLang/bcloud#17]
使用bcloud直接打开视频文件，选择使用SMPLAY为播放器时播放文件分为一段段的缓冲，大概观看11秒后缓冲一次，每个文件都是这样，与网速无关系，换成VLC可以流畅播放，但是无法前进和后退，当播放一部分后拖动播放条后退后就不能播放了

**Comment by FindHao** [comment]
如果是vlc呢？该如何设置？
