### ISSUE TITLE
ubuntu15.04中主页顶部有几个按钮显示不正常

### ISSUE THREAD

**Issue by snje1987** [LiuLang/bcloud#175]
不知道为什么，图片传不上来。
在ubuntu15.04里，主页的顶部导航按钮的底色不大正常，别的地方底色是黑的，只有那一块是白色的。

**Comment by mhohai** [comment]
关闭是没有问题么？

**Comment by snje1987** [comment]
还是有问题，不过我不确定是软件的问题还是我系统的问题，我想等确定了问题所在之后再提交问题。

gshmu <notifications@github.com>编写：

>关闭是没有问题么？ReplytothisemaildirectlyorviewitonGitHub.
