### ISSUE TITLE
关于速度issue

### ISSUE THREAD

**Issue by deartonym** [LiuLang/bcloud#176]
sorry之前写的确实不大礼貌，完全知道liulang大神的辛勤无私贡献。

-----------------------------------------

我是ubuntu14.04，除了需要绑定手机的那个账号不能登陆以外，主要的问题其实是速度的issue.

我电脑装了双系统，windows7下，下载速度能到4mb/s，一点都不卡。但是ubuntu下bcloud下载速度，很少出现吃满带宽的情况，出现过，很少，大部分都是卡着不动，偶尔会变成ERROR状态。速度几乎不能忍...

而他自己的客户端用的是别的接口？

**Comment by mhohai** [comment]
你虚拟机吧，byebye

**Comment by jtliaw** [comment]
这位朋友可能没弄清楚，百度云完全没有客户端是给linux用户的，bcloud是liulang大神自己写来让我们linux用户使用百度云下载的！bcloud使用的是网页下载方式，速度不比windows的客户端是可以理解的，毕竟百度完全没有理会linux用户。
liulang大神用了多少长的时间将bcloud优化到今天的功能，我非常感liulang！

**Comment by baoyankun** [comment]
wine windows客户端，字体被搞乱不能忍
