### ISSUE TITLE
关于bcloud的实现方式

### ISSUE THREAD

**Issue by dasenlinmutou8** [LiuLang/bcloud#178]
关注bcloud的朋友们，小弟请教几个问题：

1. bcloud 为什么能够访问“我的网盘的根目录呢？”，pcs api里面限制只能访问 “百度云端/apps/”目录下面的目录？，bcloud 貌似不是用的pcs的api，那bcloud http请求调用的api是根据什么标准来实现的呢？，比如创建目录，下载文件等，我看源码这些实现和pcs api，是不同的。

2. bcloud登录流程也不是oauth2.0,方式的，请教大神 bcloud如何实现登录授权的呢？

**Comment by mhohai** [comment]
@dasenlinmutou8 不是官方api，授权用的是浏览器（cookie 和 token），可以认为是浏览器。
只是下载时用的客户端等参数。。。

我不是作者，在具体在这个仓库搜，肯定有详细的。

**Comment by dasenlinmutou8** [comment]
mhohai，谢谢，我目前要用node-webkit来做这个类似的网盘的东西，按照bcloud的方式来实现不知道会不会有问题。
因为官方只有标准的pcs api，不知道bcloud是根据什么文档，调用的网盘接口，所以用nodejs来做，只能参考bcloud的代码实现，不知道会不会有问题。

**Comment by mhohai** [comment]
https://github.com/LiuLang/bcloud/issues/90

**Comment by dasenlinmutou8** [comment]
谢谢，您的回复，


    我还有一个问题，您的pcs.py，auth.py都是通过 python语言实现的，我用的是node-webkit的方式（js浏览器环境，属于前端开发，不能直接执行python 方法），不能很方便的直接调用你的pcs.py，和auth.py
    我想到了两个办法，请给些建议：
    1.    参考您的pcs.py和auth.py，用nodejs语言在实现一遍，这种方式还是比较麻烦的，因为向这些文件
        “from bcloud import const
        from bcloud import encoder”
        我也要去实现
    2.    nodejs，调用系统命令接口，exec('python3 py_test.py '+ arg1+' '+arg2+' ',function(error,stdout,stderr){}，直接调用python脚本，这种方式应该就可以直接
            调用pcs.py和auth.py的脚本了，但是python返回的数据如何传递到nodejs里面比较麻烦，您有没有好的方法。


   希望您给些建议，不胜感激





在 2015-09-01 08:13:42，"gshmu" <notifications@github.com> 写道：


#90

**Comment by LiuLang** [comment]
@dasenlinmutou8 
百度的登陆接口只需要看一下bcloud/auth.py, 登陆过程的加密方法看一下bcloud/util.py, 登陆流程可以看一下bcloud/SiginDialog.py.
网盘的API可以看一下bcloud/pcs.py.

这些接口都可以很容易地用node重写出来, 但如果要写界面的话, 估计会繁琐一些.

**Comment by dasenlinmutou8** [comment]
liuliang， 非常感谢！


    我现在想用一个比较简单的方法，就是nodejs通过exec(python3 xxx.py)的方式调用系统命令执行python脚本，获取到cookie和token，授权登陆这部分就不用重写了，然后pcs用node重写。
    不知道这个方法是否可行，还有就是上传下载文件这部分也需要node重写，不知道node怎么通过http请求，上传和下载文件，因为请求需要添加好多头部信息（应该不设计到加密）。


希望您能提供些建议！






在 2015-09-10 00:15:52，"LiuLang" <notifications@github.com> 写道：


@dasenlinmutou8
百度的登陆接口只需要看一下bcloud/auth.py, 登陆过程的加密方法看一下bcloud/util.py, 登陆流程可以看一下bcloud/SiginDialog.py.
网盘的API可以看一下bcloud/pcs.py.

这些接口都可以很容易地用node重写出来, 但如果要写界面的话, 估计会繁琐一些.

**Comment by LiuLang** [comment]
On 09/10/2015 10:07 AM, dasenlinmutou8 wrote:
> liuliang， 非常感谢！
>
>
>      我现在想用一个比较简单的方法，就是nodejs通过exec(python3 xxx.py)的方式调用系统命令执行python脚本，获取到cookie和token，授权登陆这部分就不用重写了，然后pcs用node重写。
>      不知道这个方法是否可行，还有就是上传下载文件这部分也需要node重写，不知道node怎么通过http请求，上传和下载文件，因为请求需要添加好多头部信息（应该不设计到加密）。
>
>
> 希望您能提供些建议！
>
>
>
>
>
>
> 在 2015-09-10 00:15:52，"LiuLang" <notifications@github.com> 写道：
>
>
> @dasenlinmutou8
> 百度的登陆接口只需要看一下bcloud/auth.py, 登陆过程的加密方法看一下bcloud/util.py, 登陆流程可以看一下bcloud/SiginDialog.py.
> 网盘的API可以看一下bcloud/pcs.py.
>
> 这些接口都可以很容易地用node重写出来, 但如果要写界面的话, 估计会繁琐一些.
>
> —
> Reply to this email directly or view it on GitHub.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LiuLang/bcloud/issues/178#issuecomment-139095220
>
用node重写的成本并不高, 反而只直用exec() 来调bcloud的接口显得没多少必要.
