### ISSUE TITLE
不能用了

### ISSUE THREAD

**Issue by anoreg** [LiuLang/bcloud#181]
最近突然要在ubuntu14.04用bcloud, 登陆时, 提示unknowerror, please try again 版本3.6, 之后我卸载, 然后装了最新的3.7依然提示这个错误, 5月份的时候还是可以正常使用的, 是不是百度最近登录需要验证手机, 所以导致客户端无法使用了

os: ubuntu14.04
checksum: ok
install method: double click .deb, install in ubuntu software center

**Comment by anoreg** [comment]
按照这个方法后, 可以继续使用, 不用绑定手机, https://github.com/gshmu/bcloud/blob/master/bcloud/auth.py

**Comment by LiuLang** [comment]
@anoreg 请更新到v3.8.1, 已经把它的代码合并到主分支了. 很抱歉拖了这么久. 详细情况请看这里, https://github.com/LiuLang/bcloud-packages/issues/172
