### ISSUE TITLE
源代码的编码问题

### ISSUE THREAD

**Issue by yorua007** [LiuLang/bcloud#182]
源代码中包含很多中文注释，但是在文件开头没有指定encoding=utf8,导致import报错

**Comment by mhohai** [comment]
@yorua007 请问你用的是python3么，一切都是unicode！！！ :8ball:

**Comment by mhohai** [comment]
:kissing_closed_eyes:  请直接关闭吧

**Comment by yorua007** [comment]
我用的python2.7，怪不得
