### ISSUE TITLE
login failure

### ISSUE THREAD

**Issue by limingy** [LiuLang/bcloud#190]
在异地登录的时候，要求输入验证码，但是即使输入验证码，也无法登录。
提示：不支持手机短信/邮件验证！

版本：3.8.1-1.1

**Comment by LiuLang** [comment]
那你之前有绑定过手机么?

**Comment by ccpaging** [comment]
出现同样的问题。解绑手机后正常。

**Comment by limingy** [comment]
您好，通过实验觉得这个不算是问题了吧，“提示：不支持手机短信/邮件验证！”
也就是说，现在你要是用网页客户端登录重新登录，它需要手机验证，验证通过了。
然后你再用bcloud登录就应该没问题了。

**Comment by ccpaging** [comment]
bcloud出现登录问题时，我用web登录网页，网页上跳出手机验证，验证并确认无误后，返回bcloud。

**Comment by LiuLang** [comment]
这样操作也行, 只是比较麻烦.
