### ISSUE TITLE
不能更换下载的路径吗，找不到在哪里设置

### ISSUE THREAD

**Issue by wcy95** [LiuLang/bcloud#193]
只有在刚开始安装的时候有一个首选项的对话框，设置完之后就再也找不到了，难道是只能一次性设置？而且下载总是会错误，速度也不稳定，有时候很快有时候又为0，今天下载的时候还出现了下载到一半暂停又开始后竟然又从头开始下载了

**Comment by mhohai** [comment]
就一个设置的地方，你说你找不到。。。  你用的什么系统？

**Comment by wcy95** [comment]
![image](https://cloud.githubusercontent.com/assets/9800126/10448422/5b7515ca-71bf-11e5-95e6-0991706e3ef4.png)
ubuntu14.04

**Comment by mhohai** [comment]
![screenshot from 2015-10-13 17 42 36](https://cloud.githubusercontent.com/assets/1797676/10451292/dfac47c0-71d1-11e5-85ec-ca064a140ac3.png)
Ubuntu 最顶上，左侧。。。

**Comment by wcy95** [comment]
@mhohai 谢啦，原来要最大化之后才有

**Comment by mhohai** [comment]
@wcy95 跟最大化没有关系吧？  Ubuntu的活动窗口的菜单栏默认在最顶部。
问题解决自觉关issue :8ball:
