### ISSUE TITLE
does not work in fedora 23

### ISSUE THREAD

**Issue by 1dot75cm** [LiuLang/bcloud#196]
Fedora 23 运行 bcloud ，终端出现假死， bcloud-stderr.log 没有任何内容。 希望重构后，解决此问题。

相关软件版本：
- libgnome-keyring 3.12
- gtk3 3.18.2
- python3-crypto 2.6.1
- python3-dbus 1.2.0
- python3-gobject-base 3.18.0
- python3-inotify 0.9.6
- python3-keyring 5.0

**Comment by kylinfedora** [comment]
我这也是

**Comment by mytc** [comment]
我的也是阿。

**Comment by songxinqiang** [comment]
我的fedora23直接启动不了，点击图标之后鼠标指针更改为等待，稍后恢复，bcloud的进程是在后台运行的，但是不能正常使用

**Comment by yejingchen** [comment]
一样的情况，用命令行运行连 control + C 都退出不了，只能用 `pkill` 强行杀掉

此外也有 PyGIWarning(https://github.com/LiuLang/bcloud/issues/198)

**Comment by mytc** [comment]
找到问题所在了。原来是需要sudo / su 来运行 bcloud-gui 才可以。这时终端会出现输入gnome-keyring的命令。我想问题因该是在这儿。

**Comment by 1dot75cm** [comment]
经测试，Gnome 上游已修正 bug。只要更新至最新版本，bcloud 即可正常使用。

相关软件版本：
- libgnome-keyring 3.12
- gtk3 3.18.6  更新～
- python3-crypto 2.6.1
- python3-dbus 1.2.0
- python3-gobject-base 3.18.2  更新～
- python3-inotify 0.9.6
- python3-keyring 5.0

> 找到问题所在了。原来是需要sudo / su 来运行 bcloud-gui 才可以。这时终端会出现输入gnome-keyring的命令。我想问题因该是在这儿。 

千万不要使用 sudo 运行 GUI 程序。

**Comment by LiuLang** [comment]
请不要用sudo/su 来强制运行bcloud ;-(
