### ISSUE TITLE
PyGIWarning

### ISSUE THREAD

**Issue by yan12125** [LiuLang/bcloud#198]
I got some warnings at startup:
```
$ bcloud-gui
sys:1: PyGIWarning: Gdk was imported without specifying a version first. Use gi.require_version('Gdk', '3.0') before import to ensure that the right version gets loaded.
sys:1: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
sys:1: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
```

Environment:
Arch Linux x86_64
Python 3.5.0
python-gobject 3.18.2

**Comment by LiuLang** [comment]
On 11/01/2015 01:26 AM, Yen Chi Hsuan wrote:
> I got some warnings at startup:
> ```
> $ bcloud-gui
> sys:1: PyGIWarning: Gdk was imported without specifying a version first. Use gi.require_version('Gdk', '3.0') before import to ensure that the right version gets loaded.
> sys:1: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
> sys:1: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
> ```
>
> Environment:
> Arch Linux x86_64
> Python 3.5.0
> python-gobject 3.18.2
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LiuLang/bcloud/issues/198
>
这个警告是由于python3-gi 更新后出现的.

最近正在重构bcloud, 这个问题也会一并被修正的, 谢谢你的反馈.

**Comment by LiuLang** [comment]
https://github.com/LiuLang/bcloud/commit/1017728c90a459f853d9b4c29d3c3563a5512b06
已经处理了

**Comment by yan12125** [comment]
Tested with the latest git commit and the warnings are gone. Thanks for fixing it!
