### ISSUE TITLE
菜单项目图标icon无法正常显示

### ISSUE THREAD

**Issue by wxg4net** [LiuLang/bcloud#20]
界面截图 http://t.cn/8sDNoEb
版本：git
系统：arch
Strace：http://mservice-perhome.stor.sinaapp.com/bclound.strace

**Comment by mhohai** [comment]
我的黑色主题不显示，有谁知道怎么破么？  system: Ubuntu 64 14.04
![dark](https://clbin.com/Gp8IGt.png)

**Comment by wxg4net** [comment]
@mhohai  我从来没体会过 黑色主题是啥样子的..

**Comment by mhohai** [comment]
@wxg4net 我就是想提现下，结果是上图那个样子 :sob:

**Comment by mhohai** [comment]
@imzf 感谢回复
