### ISSUE TITLE
能否对如何用命令行登录和下载举一个小例子。

### ISSUE THREAD

**Issue by weyless** [LiuLang/bcloud#202]
您好，看了您给出的遍历目录的方法，但是对如何在命令行的情况下使用bcloud还是不很明白。
尤其是下载模块是单独分出去的，请问能否简单的给个例子讲一下如何比较简单的登录和下载文件

**Comment by LiuLang** [comment]
On 11/05/2015 06:24 PM, weyless wrote:
> 您好，看了您给出的遍历目录的方法，但是对如何在命令行的情况下使用bcloud还是不很明白。
> 尤其是下载模块是单独分出去的，请问能否简单的给个例子讲一下如何比较简单的登录和下载文件
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LiuLang/bcloud/issues/202
>
最近正在重构bcloud, 它的一些使用方法可能会作出变更, 请等我重构结束之后再 
回复这个问题, 可以吧?

**Comment by weyless** [comment]
十分感谢！
