### ISSUE TITLE
最近不能登陆了

### ISSUE THREAD

**Issue by freealong** [LiuLang/bcloud#210]
![screenshot from 2015-11-24 17 43 34](https://cloud.githubusercontent.com/assets/8717689/11363140/e9dcf8c6-92d2-11e5-9d28-0a969f7d674e.png)

**Comment by wangjiezhe** [comment]
我有两个账号，一个绑定了手机，一个没绑定。以前是没绑定手机的登不了，现在是绑定了手机的登不了。。。

**Comment by mhohai** [comment]
你是说，现在 绑定了手机的登录不了，没绑定的能登录？

**Comment by wangjiezhe** [comment]
今天是这样

**Comment by freealong** [comment]
好了。。。
