### ISSUE TITLE
突然之间Failed to get bdstoken!

### ISSUE THREAD

**Issue by mytc** [LiuLang/bcloud#213]
用的好好的，不知道为什么突然不能登陆， 出现这个error: Failed to get bdstoken!
已经好几天了。
我的系统是Fedora 23 , Mate DE.

**Comment by wangjiezhe** [comment]
同样问题，几天前还是正常的。

没有绑定手机的账号显示 Failed to get bdstoken
日志为
```
ERROR SigninDialog.on_get_bdstoken: , None
```

绑定了手机的先是弹出验证码，输入后显示 Unknown error, please try again
日志为
```
ERROR SigninDialog.on_post_login: (400037, None), None
```

**Comment by klaaswang** [comment]
遭遇了同样的问题。debian

**Comment by mhohai** [comment]
我网页登录，多了个验证码，诸位意下如何。。。

**Comment by eshion** [comment]
遭遇了同样的问题, archlinux

**Comment by jtliaw** [comment]
Lubuntu同样的问题！

**Comment by mhohai** [comment]
可以修改文件测试啊：https://github.com/LiuLang/bcloud/pull/214/files

**Comment by ivo-wang** [comment]
不错，问题解决了

**Comment by s75671** [comment]
fedora23通过修改/usr/lib/python3.4/site-packages/bcloud/auth.py 解决+1

**Comment by ccpaging** [comment]
@mhohai 谢谢。问题解决了。

**Comment by mhohai** [comment]
@ccpaging 不是我更新的，谢的我都不好意思了。

**Comment by jtliaw** [comment]
谢谢更新的大神！
Lubuntu位置：/usr/lib/python3/dist-packages/bcloud/auth.py

**Comment by mhohai** [comment]
看大家发path，我也来一发。
```
$ python3
>>> from bcloud import auth
>>> auth.__file__
'/usr/lib/python3/dist-packages/bcloud/auth.py'```

**Comment by mytc** [comment]
Fixed!! 谢谢！！！

**Comment by windilt** [comment]
opensuse 42.1解决
不过bcloud-3.8.1还没有更新这个代码

**Comment by ccpaging** [comment]
Archlinux64
```python
$python3
Python 3.5.1 (default, Dec  7 2015, 12:58:09) 
[GCC 5.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from bcloud import auth
sys:1: PyGIWarning: Gdk was imported without specifying a version first. Use gi.require_version('Gdk', '3.0') before import to ensure that the right version gets loaded.
sys:1: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
>>> auth.__file__
'/usr/lib/python3.5/site-packages/bcloud/auth.py'
```

**Comment by William17** [comment]
谢谢 +1
`/usr/lib/python3/dist-packages/bcloud/auth.py`

**Comment by cleardusk** [comment]
https://github.com/LiuLang/bcloud/pull/214/files
原来是正则匹配的问题==，这个 issue 应该可以 close 了吧～

**Comment by meiavy** [comment]
谢谢，修改文件后ok了。centos7

**Comment by mhohai** [comment]
@cleardusk 按理改关了，但是按照你国的搜索习惯，暂时开着吧。

**Comment by ljmdztx** [comment]
Linux mint 17.3，修改文件后OK 了，同样的问题。再次感谢大家的热心讨论。

**Comment by sorrowchen** [comment]
DESCRIPTION="Linux Mint 17.1 Rebecca"
修改完却仍然提示无法获取bdstoken
# pwd
/usr/lib/python3/dist-packages/bcloud
# grep bdstoken   auth.py 
...
    bds_re = re.compile('bdstoken\s*:\s*"([^"]+)"',re.IGNORECASE)
        bdstoken = bds_match.group(1)
    return bdstoken

**Comment by wangjiezhe** [comment]
@sorrowchen 少了两个星号。。。

**Comment by sorrowchen** [comment]
@wangjiezhe ![2015-12-24 14 41 54](https://cloud.githubusercontent.com/assets/1155127/11990706/8bfcd9ec-aa4c-11e5-84e1-4ad66405683b.png)
发的时候不知道为啥, 代码被修正了似的, 这是截图, 我还把__pycache__里的内容都清空了. 换root和普通权限去执行, 也还是一样情况. 觉得不一致的地方就是我的这行代码是第276行, 和git文件里的是第278行

**Comment by wangjiezhe** [comment]
@sorrowchen github 把两个 \* 默认成强调符号了。。。
应该是 `"bdstoken"`，少了双引号。

**Comment by sorrowchen** [comment]
@wangjiezhe 谢谢, 重新安装了3.8.1-1_all这个包, 再按你说的, 搞定了. 
:+1:

**Comment by LiuLang** [comment]
很抱歉, 最近开了新项目. 原本是打算重构bcloud的, 但现在看来, 过年之前是没时间了. 很抱歉让各位久等了.
现在在和网易合作开发linux版的网易云音乐, 估计到1月底能发正式版.

**Comment by LiuLang** [comment]
已经合并了代码, 并且生成了v3.8.2版, deb包也制作好了, 有需要的朋友可以更新下.

**Comment by DeveloperZhou** [comment]
好期待网易的linux版。ha

**Comment by AndySpider** [comment]
Ubuntu14.04 64bit，已经安装了最新的bcloud_3.8.2-1_all.deb，还是报"Failed to get bdstoken!"。
根据上面的讨论检查auth.py文件是正确的。
![auto_py](https://cloud.githubusercontent.com/assets/2025182/12220702/06b1ca86-b7b7-11e5-9840-f4eb0d47b9c2.png)

**Comment by gshmu** [comment]
都问百度去，哈哈

**Comment by einverne** [comment]
使用 https://github.com/LiuLang/bcloud/pull/214/files 果然能够解决，感谢
