### ISSUE TITLE
登陆验证码是中文的了

### ISSUE THREAD

**Issue by pingplug** [LiuLang/bcloud#255]
今天发现登陆验证码变成中文了，该修改一下检查验证码的部分了

**Comment by pingplug** [comment]
看了一下，好像是检查了验证码是不是四位。。。然而中文验证码是两个字。。。

**Comment by poplite** [comment]
可以修改代码取消检查验证码长度：
1.SigninDialog.py的第322行和386行：
`if not verifycode or len(verifycode) != 4:`改为`if not verifycode:`
2.SigninDialog.py的第118行：

```
    def on_vcode_confirm_clicked(self, button):
        self.check_entry()
```

改为

```
    def on_vcode_confirm_clicked(self, button):
        self.response(Gtk.ResponseType.OK)
```

**Comment by poplite** [comment]
其实刷新一下验证码就会有原来的四位验证码出现，只是程序有bug不能刷新而已。

修复bug：
SigninDialog.py第315行的`tokens['token']`改为`tokens`

**Comment by lineex** [comment]
@poplite 感谢   每次遇到的问题你都能及时解决  感谢

**Comment by sorrowchen** [comment]
@poplite 貌似修复bug的那个办法不成功, 在获取验证码之前卡住了. 
第一种办法奏效..谢谢

**Comment by DW2993706602** [comment]
@poplite 感激感激，问题解决了
