### ISSUE TITLE
无法登陆,显示无法获取bdstoken

### ISSUE THREAD

**Issue by TiDao** [LiuLang/bcloud#267]
我看了报错
urllib.error.HTTPError: HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Found

2017-01-19 17:27:17,861 ERROR SigninDialog.on_get_bdstoken: None, None

**Comment by hency** [comment]
我也碰到了，早上到中午还好好的

**Comment by TiDao** [comment]
@hency 这里这个好久没人维护了,有另一个哥们开了一个fork,说是在维护,但是他没打开issues.....也无法反应问题https://github.com/Yufeikang/bcloud ,看报的问题应该是百度升级了某些东西,导致软件拿不到返回结果

**Comment by hency** [comment]
@TiDao 我就是先装的这个再装的Yufeikang的补丁才用上的百度云，看到你说的我也附和一下

**Comment by TiDao** [comment]
@hency 你的问题解决了么?

**Comment by kkzxak47** [comment]
感觉像百度有意返回无限302阻止登录，是不是有些参数需要更新了。

**Comment by poplite** [comment]
302转跳时没有带上cookie导致验证没有通过，不断302重定向到了登录链接。

**Comment by poplite** [comment]
不知道已经绑定手机的账号会不会出现这样的问题。

**Comment by hency** [comment]
@TiDao 没解决
@poplite 我账号就绑定了手机的，仍然不行

**Comment by poplite** [comment]
看来只能拦截重定向了。。。
涉及的代码很多，不知道能不能发patch。。。

**Comment by kkzxak47** [comment]
我感觉网络请求部分的cookie写得有点麻烦啊，手动传来传去的，现在也不好改

**Comment by poplite** [comment]
@kkzxak47 不如直接用`http.cookiejar`自动处理好，但是这样要重写bcloud了。。。

**Comment by poplite** [comment]
PATCH:`https://gist.github.com/poplite/72f76df4f9d9f1622f73b786937fe389`
没有修改GUI界面。对比自bcloud的master分支。

**Comment by yinflying** [comment]
@poplite 你的补丁的网址我打不开哇。
百度云盘做了一次不小的变更，连我以前的老版本的百度云盘windwos版都没有办法用了。

**Comment by poplite** [comment]
@yinflying 我把它发在Ubuntu pastebin上了:`https://paste.ubuntu.com/23972254/`
patch是跟原master分支对比的，我只在自己的设备上测试通过。
我没有用过win版的客户端。就网页端的变化来看，只是登录后通过302转跳获得额外需要的cookie(不知道原来有没有这个转跳)。

**Comment by yinflying** [comment]
@poplite 按照补丁打完之后，依旧报错。 不过毕竟使用的少，先不管了。

**Comment by poplite** [comment]
@yinflying 我在https://github.com/Yufeikang/bcloud/commit/0484ce312803ee5917366c272caff3a0e957f0c4 看到了你的评论，可以告诉我具体情况吗？

**Comment by poplite** [comment]
@yinflying 如果确认修改无误的话，可以试一下取消修改后的SigninDialog.py第301行，第318行的注释，看看登录时出不出现`Get access cookie...`和查看日志。

**Comment by yinflying** [comment]
@poplite 在取消注释之后，终端的错误：[https://paste.ubuntu.com/23979857/](https://paste.ubuntu.com/23979857/)
不过我是基于Yufeikang的版本修改的，可能有所出入。

**Comment by yufeikang** [comment]
已经修复这个问题，请移步：https://github.com/Yufeikang/bcloud/releases/tag/v3.9.1

**Comment by yinflying** [comment]
@Yufeikang 感谢！ 但是不知道为什么我的出现下面错误：
`2017-02-12 20:49:41,712 ERROR SigninDialog.on_post_login: (7, None), None`
然后多次尝试之后现在忽然现“因为登录次数过多，到password.baidu.com解锁”，郁闷中。

**Comment by yinflying** [comment]
@Yufeikang 感谢，可以使用了。

ubuntu/debian用户可试试我的打包：[https://github.com/yinflying/bcloud-packages](https://github.com/yinflying/bcloud-packages)

**Comment by weichuanqianmu** [comment]
@yinflying 求教怎麼打包？我只會裝有./configure, 或者make . 的。[盈盈期盼的眼神]

**Comment by yinflying** [comment]
@weichuanqianmu 自己解一个包看看就知道怎么打包了。本质就是将包内文件分配到相应的目录中去，和make install是相同的。不过打包后会带有包内文件的位置信息、版本信息以及依赖信息等，方便控制和管理。
对于debian来说，dpkg-deb可以打包，自己看看用法吧。

**Comment by poplite** [comment]
@yinflying patch是基于LiuLang的master分支写的，Yufeikang的版本可能不适用。(抱歉，最近很忙，刚刚才抽出时间回复。。。)

**Comment by TiDao** [comment]
问题已经解决,使用这个版本https://github.com/Yufeikang/bcloud/releases/tag/v3.9.1

**Comment by zhangxulong** [comment]
yes this works @TiDao 问题已经解决,使用这个版本https://github.com/Yufeikang/bcloud/releases/tag/v3.9.1
