### ISSUE TITLE
 ERROR SigninDialog.on_post_login: (5, None), None   无法登陆

### ISSUE THREAD

**Issue by TiDao** [LiuLang/bcloud#270]
题目就是报错;我尝试找到错误代码,但是没有搜到

**Comment by yinflying** [comment]
同遇到这种错误，不出现现验证码，坐等大神来解决。

难怪LiuLang弃坑，三天两头变更一下，果断还是直接使用网页版。。。

**Comment by TiDao** [comment]
@yinflying 可是网页有限速啊,我的带宽都在白白浪费,感觉并不是百度那边的问题如果是他问题的话,他自己的软件也受不了,难道百度内部还有自己使用的一套API ?

**Comment by levinit** [comment]
我的使用方法是：小文件就用网页版用浏览器或者调用其他软件如uget或pointdownload下载，大文件就用baidupcs-git下载。一堆小文文件就下载让浏览器打包成压缩包下，一堆大文件-_-!

**Comment by willhunger** [comment]
`
(bcloud-gui:7893): Gtk-WARNING **: (/build/gtk+3.0-VoKwSM/gtk+3.0-3.20.9/./gtk/gtkicontheme.c:2184):gtk_icon_theme_choose_icon: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
2017-03-04 15:36:56,254 ERROR SigninDialog.on_post_login: (5, None), None

`
目前的错误如上,请求@Yufeikang 来修复

**Comment by caasiu** [comment]
修改auth.py文件 `post_login` 函数里面 [data](https://github.com/LiuLang/bcloud/blob/master/bcloud/auth.py#L216) 对应地方为以下值：
```
'staticpage=http%3A%2F%2Fyun.baidu.com%2Fres%2Fstatic%2Fthirdparty%2Fpass_v3_jump.html',
'tpl=netdisk',
'subpro=netdisk_web',
'u=http%3A%2F%2Fyun.baidu.com%2Fdisk%2Fhome',
```

**Comment by lowy** [comment]
@caasiu 照着改了也没反应 咋回事

**Comment by feitianbajie** [comment]
按上面的方法修改已经成功登录。

**Comment by weichuanqianmu** [comment]
@feitianbajie 把你改的data 整個貼上來吧。

**Comment by DW2993706602** [comment]
/usr/local/lib/python3.5/dist-packages/bcloud/App.py:45: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.

App.py第45行出错，但是我并不知道怎么修改

**Comment by feitianbajie** [comment]
@weichuanqianmu 修改的data项

    data = ''.join([
        'staticpage=http%3A%2F%2Fyun.baidu.com%2Fres%2Fstatic%2Fthirdparty%2Fpass_v3_jump.html',
        'tpl=netdisk',
        'subpro=netdisk_web',
        'u=http%3A%2F%2Fyun.baidu.com%2Fdisk%2Fhome',        
        '&charset=UTF-8',
        '&token=', tokens['token'],
        '&apiver=v3',
        '&tt=', util.timestamp(),
        '&codestring=', codestring,
        '&safeflg=0&u=http%3A%2F%2Fwww.baidu.com%2F',
        '&isPhone=false',
        '&quick_user=0&logintype=baseLogin&logLoginType=pc_loginBasic&idc=',
        '&loginmerge=true',
        '&username=', encoder.encode_uri_component(username),
        '&password=', encoder.encode_uri_component(password),
        '&verifycode=', verifycode,
        '&mem_pass=on',
        '&rsakey=', rsakey,
        '&crypttype=12',
        '&ppui_logintime=', get_ppui_logintime(),
        '&callback=parent.bd__pcbs__28g1kg',
    ])

**Comment by lowy** [comment]
验证码的提交与刷新没反应
![deepinscrot-1407](https://cloud.githubusercontent.com/assets/6565177/23689953/fb152d64-03f8-11e7-9062-b8e1a8a102f8.png)
![deepinscrot-1425](https://cloud.githubusercontent.com/assets/6565177/23689959/03e46f9a-03f9-11e7-91a8-ef63636529f7.png)

**Comment by weichuanqianmu** [comment]
@feitianbajie 多謝。

**Comment by feitianbajie** [comment]
@lowy 按我上面的改data项还是没有办法登录吗？

**Comment by lowy** [comment]
@feitianbajie 嗯 不过好一点 没改之前连验证码都没有

**Comment by feitianbajie** [comment]
@lowy  你安装的是最新的版本吗？

**Comment by TiDao** [comment]
问题解决感谢 @caasiu 和 @feitianbajie

**Comment by caasiu** [comment]
好像现在要在data项里面加入`dv`的值，否则还是提示错误代码5。
你们是这样吗？

**Comment by feitianbajie** [comment]
我没有加入DV的值不过我把最后的逗号删掉了就又可以登入了。

**Comment by poplite** [comment]
试试用缓存的授权信息登录:https://github.com/poplite/bcloud/commit/420ec613146625e019809cd93dfafaf5241594aa 授权信息的有效期差不多有一年

**Comment by liu-xiao-guo** [comment]
＠lowy 我的和你的是一样的，提示验证码后就再也没有新的动作了。你解决你的问题了吗？谢谢！

**Comment by yinflying** [comment]
@liu-xiao-guo 直接使用Yufeikang的版本即可，他已经修复了。
如果是debian/ubuntu用户，可以试试我打包的版本：当然，我可不是一个维护者，我就是怎么能用怎么来。https://github.com/yinflying/bcloud-packages

**Comment by lowy** [comment]
@liu-xiao-guo 楼上@yinflying的修复包已经解决了

**Comment by liu-xiao-guo** [comment]
谢谢回到，我已经解决这个问题了。我已经做好一个snap版本的应用了。 

    On Friday, March 17, 2017 3:18 PM, yinflying <notifications@github.com> wrote:
 

 @liu-xiao-guo 直接使用Yufeikang的版本即可，他已经修复了。
如果是debian/ubuntu用户，可以试试我打包的版本：当然，我可不是一个维护者，我就是怎么能用怎么来。https://github.com/yinflying/bcloud-packages—
