### ISSUE TITLE
Failed to get bdstoken

### ISSUE THREAD

**Issue by chaopeng** [LiuLang/bcloud#42]

**Comment by SeaflyDennis** [comment]
我的同样也是，执行bcloud-gui后，输入账号密码之后，一直卡在get bdstoken位置，最后提示Failed to get bdstoken

**Comment by SeaflyDennis** [comment]
我的是ubuntu14.04 64位，2017-07-01获取的克隆包，但还是卡在get bdstoken并且最终出现错误提示：Failed to get bdstoken

**Comment by seaflygithub** [comment]
我的是ubuntu14.04 64位，2017-07-01获取的克隆包，但还是卡在get bdstoken并且最终出现错误提示：Failed to get bdstoken，要是这个反馈能传截图就好了。。。

**Comment by poplite** [comment]
@SeaflyDennis bcloud已经停止维护两年多了，有一大堆bug没有修复。
其实@LiuLang已经在断断续续地重写bcloud了：https://github.com/LiuLang/bcloud/commits/ts
现在只有@Yufeikang的版本还在活跃维护中，你可以用他的：https://github.com/Yufeikang/bcloud

**Comment by poplite** [comment]
@SeaflyDennis 有兴趣的话看看我自己维护的版本：https://github.com/poplite/bcloud
